// lib/google-sheets.ts

import { Application, ApplicationStatus } from './types';

// In-memory mock data
let MOCK_DATA: Application[] = [
  {
    "applicationId": "APP-001",
    "timestamp": "2026-09-09T11:19:09.964588Z",
    "status": "Selected",
    "fullName": "Peter Moore",
    "registrationNumber": "12000001",
    "universityEmail": "peter.moore@university.edu",
    "personalEmail": "peter.moore@gmail.com",
    "phone": "9876529498",
    "program": "BBA",
    "branch": "Electronics",
    "semester": "2",
    "cgpa": "6.7",
    "linkedin": "https://linkedin.com/in/petermoore",
    "github": "https://github.com/petermoore",
    "portfolio": "https://petermoore.dev",
    "preferredRole": "DevOps Engineer",
    "resumeUrl": "https://example.com/resume1.pdf",
    "resumeFileId": "file_001",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "1 years"
    },
    "ipAddress": "192.168.1.1",
    "communities": "AWS Cloud Club",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 2
  },
  {
    "applicationId": "APP-002",
    "timestamp": "2026-09-08T11:19:09.964629Z",
    "status": "Shortlisted",
    "fullName": "Peter Lopez",
    "registrationNumber": "12000002",
    "universityEmail": "peter.lopez@university.edu",
    "personalEmail": "peter.lopez@gmail.com",
    "phone": "9876570380",
    "program": "M.Tech",
    "branch": "Civil",
    "semester": "5",
    "cgpa": "8.4",
    "linkedin": "https://linkedin.com/in/peterlopez",
    "github": "https://github.com/peterlopez",
    "portfolio": "",
    "preferredRole": "Marketing",
    "resumeUrl": "https://example.com/resume2.pdf",
    "resumeFileId": "file_002",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.2",
    "communities": "IEEE",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 3
  },
  {
    "applicationId": "APP-003",
    "timestamp": "2026-08-27T11:19:09.964641Z",
    "status": "Rejected",
    "fullName": "Jack Johnson",
    "registrationNumber": "12000003",
    "universityEmail": "jack.johnson@university.edu",
    "personalEmail": "jack.johnson@gmail.com",
    "phone": "9876595918",
    "program": "M.Tech",
    "branch": "Electronics",
    "semester": "4",
    "cgpa": "7.7",
    "linkedin": "https://linkedin.com/in/jackjohnson",
    "github": "https://github.com/jackjohnson",
    "portfolio": "",
    "preferredRole": "Data Scientist",
    "resumeUrl": "https://example.com/resume3.pdf",
    "resumeFileId": "file_003",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "2 years"
    },
    "ipAddress": "192.168.1.3",
    "communities": "IEEE",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 4
  },
  {
    "applicationId": "APP-004",
    "timestamp": "2026-08-23T11:19:09.964648Z",
    "status": "Pending",
    "fullName": "Jack Rodriguez",
    "registrationNumber": "12000004",
    "universityEmail": "jack.rodriguez@university.edu",
    "personalEmail": "jack.rodriguez@gmail.com",
    "phone": "9876586296",
    "program": "B.Tech",
    "branch": "Information Technology",
    "semester": "5",
    "cgpa": "6.9",
    "linkedin": "https://linkedin.com/in/jackrodriguez",
    "github": "https://github.com/jackrodriguez",
    "portfolio": "https://jackrodriguez.dev",
    "preferredRole": "Frontend Developer",
    "resumeUrl": "https://example.com/resume4.pdf",
    "resumeFileId": "file_004",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.4",
    "communities": "Open Source Society",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 5
  },
  {
    "applicationId": "APP-005",
    "timestamp": "2026-08-26T11:19:09.964654Z",
    "status": "Pending",
    "fullName": "Eva Brown",
    "registrationNumber": "12000005",
    "universityEmail": "eva.brown@university.edu",
    "personalEmail": "eva.brown@gmail.com",
    "phone": "9876556053",
    "program": "BBA",
    "branch": "Computer Science",
    "semester": "5",
    "cgpa": "7.2",
    "linkedin": "https://linkedin.com/in/evabrown",
    "github": "https://github.com/evabrown",
    "portfolio": "https://evabrown.dev",
    "preferredRole": "DevOps Engineer",
    "resumeUrl": "https://example.com/resume5.pdf",
    "resumeFileId": "file_005",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.5",
    "communities": "GDSC",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 6
  },
  {
    "applicationId": "APP-006",
    "timestamp": "2026-09-01T11:19:09.964660Z",
    "status": "Pending",
    "fullName": "Henry Miller",
    "registrationNumber": "12000006",
    "universityEmail": "henry.miller@university.edu",
    "personalEmail": "henry.miller@gmail.com",
    "phone": "9876560636",
    "program": "M.Tech",
    "branch": "Computer Science",
    "semester": "8",
    "cgpa": "9.7",
    "linkedin": "https://linkedin.com/in/henrymiller",
    "github": "https://github.com/henrymiller",
    "portfolio": "https://henrymiller.dev",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume6.pdf",
    "resumeFileId": "file_006",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "1 years"
    },
    "ipAddress": "192.168.1.6",
    "communities": "GDSC",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 7
  },
  {
    "applicationId": "APP-007",
    "timestamp": "2026-09-08T11:19:09.964666Z",
    "status": "Interview Scheduled",
    "fullName": "Henry Wilson",
    "registrationNumber": "12000007",
    "universityEmail": "henry.wilson@university.edu",
    "personalEmail": "henry.wilson@gmail.com",
    "phone": "9876526640",
    "program": "BBA",
    "branch": "Computer Science",
    "semester": "7",
    "cgpa": "7.5",
    "linkedin": "https://linkedin.com/in/henrywilson",
    "github": "https://github.com/henrywilson",
    "portfolio": "https://henrywilson.dev",
    "preferredRole": "Data Scientist",
    "resumeUrl": "https://example.com/resume7.pdf",
    "resumeFileId": "file_007",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "3 years"
    },
    "ipAddress": "192.168.1.7",
    "communities": "IEEE",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 8
  },
  {
    "applicationId": "APP-008",
    "timestamp": "2026-08-31T11:19:09.964673Z",
    "status": "Pending",
    "fullName": "Karen Miller",
    "registrationNumber": "12000008",
    "universityEmail": "karen.miller@university.edu",
    "personalEmail": "karen.miller@gmail.com",
    "phone": "9876546488",
    "program": "BBA",
    "branch": "Information Technology",
    "semester": "6",
    "cgpa": "8.8",
    "linkedin": "https://linkedin.com/in/karenmiller",
    "github": "https://github.com/karenmiller",
    "portfolio": "https://karenmiller.dev",
    "preferredRole": "DevOps Engineer",
    "resumeUrl": "https://example.com/resume8.pdf",
    "resumeFileId": "file_008",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "1 years"
    },
    "ipAddress": "192.168.1.8",
    "communities": "IEEE",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 9
  },
  {
    "applicationId": "APP-009",
    "timestamp": "2026-09-13T11:19:09.964679Z",
    "status": "Interview Scheduled",
    "fullName": "Ivy Smith",
    "registrationNumber": "12000009",
    "universityEmail": "ivy.smith@university.edu",
    "personalEmail": "ivy.smith@gmail.com",
    "phone": "9876542290",
    "program": "MCA",
    "branch": "Computer Science",
    "semester": "5",
    "cgpa": "8.9",
    "linkedin": "https://linkedin.com/in/ivysmith",
    "github": "https://github.com/ivysmith",
    "portfolio": "",
    "preferredRole": "Data Scientist",
    "resumeUrl": "https://example.com/resume9.pdf",
    "resumeFileId": "file_009",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "2 years"
    },
    "ipAddress": "192.168.1.9",
    "communities": "AWS Cloud Club",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 10
  },
  {
    "applicationId": "APP-010",
    "timestamp": "2026-08-30T11:19:09.964684Z",
    "status": "Selected",
    "fullName": "Bob Jackson",
    "registrationNumber": "12000010",
    "universityEmail": "bob.jackson@university.edu",
    "personalEmail": "bob.jackson@gmail.com",
    "phone": "9876543368",
    "program": "BBA",
    "branch": "Mechanical",
    "semester": "4",
    "cgpa": "8.2",
    "linkedin": "https://linkedin.com/in/bobjackson",
    "github": "https://github.com/bobjackson",
    "portfolio": "https://bobjackson.dev",
    "preferredRole": "Marketing",
    "resumeUrl": "https://example.com/resume10.pdf",
    "resumeFileId": "file_010",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.10",
    "communities": "ACM",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 11
  },
  {
    "applicationId": "APP-011",
    "timestamp": "2026-09-14T11:19:09.964691Z",
    "status": "Shortlisted",
    "fullName": "Jack Miller",
    "registrationNumber": "12000011",
    "universityEmail": "jack.miller@university.edu",
    "personalEmail": "jack.miller@gmail.com",
    "phone": "9876516515",
    "program": "M.Tech",
    "branch": "Mechanical",
    "semester": "8",
    "cgpa": "8.9",
    "linkedin": "https://linkedin.com/in/jackmiller",
    "github": "https://github.com/jackmiller",
    "portfolio": "",
    "preferredRole": "Data Scientist",
    "resumeUrl": "https://example.com/resume11.pdf",
    "resumeFileId": "file_011",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "2 years"
    },
    "ipAddress": "192.168.1.11",
    "communities": "Open Source Society",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 12
  },
  {
    "applicationId": "APP-012",
    "timestamp": "2026-08-21T11:19:09.964696Z",
    "status": "Rejected",
    "fullName": "David Martinez",
    "registrationNumber": "12000012",
    "universityEmail": "david.martinez@university.edu",
    "personalEmail": "david.martinez@gmail.com",
    "phone": "9876533527",
    "program": "BBA",
    "branch": "Civil",
    "semester": "1",
    "cgpa": "7.4",
    "linkedin": "https://linkedin.com/in/davidmartinez",
    "github": "https://github.com/davidmartinez",
    "portfolio": "",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume12.pdf",
    "resumeFileId": "file_012",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "3 years"
    },
    "ipAddress": "192.168.1.12",
    "communities": "Open Source Society",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 13
  },
  {
    "applicationId": "APP-013",
    "timestamp": "2026-09-08T11:19:09.964702Z",
    "status": "Rejected",
    "fullName": "David Jones",
    "registrationNumber": "12000013",
    "universityEmail": "david.jones@university.edu",
    "personalEmail": "david.jones@gmail.com",
    "phone": "9876590925",
    "program": "MCA",
    "branch": "Civil",
    "semester": "7",
    "cgpa": "8.6",
    "linkedin": "https://linkedin.com/in/davidjones",
    "github": "https://github.com/davidjones",
    "portfolio": "https://davidjones.dev",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume13.pdf",
    "resumeFileId": "file_013",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "1 years"
    },
    "ipAddress": "192.168.1.13",
    "communities": "AWS Cloud Club",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 14
  },
  {
    "applicationId": "APP-014",
    "timestamp": "2026-09-01T11:19:09.964706Z",
    "status": "Selected",
    "fullName": "Frank Miller",
    "registrationNumber": "12000014",
    "universityEmail": "frank.miller@university.edu",
    "personalEmail": "frank.miller@gmail.com",
    "phone": "9876519476",
    "program": "MCA",
    "branch": "Civil",
    "semester": "7",
    "cgpa": "6.8",
    "linkedin": "https://linkedin.com/in/frankmiller",
    "github": "https://github.com/frankmiller",
    "portfolio": "",
    "preferredRole": "DevOps Engineer",
    "resumeUrl": "https://example.com/resume14.pdf",
    "resumeFileId": "file_014",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.14",
    "communities": "ACM",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 15
  },
  {
    "applicationId": "APP-015",
    "timestamp": "2026-09-04T11:19:09.964711Z",
    "status": "Pending",
    "fullName": "Grace Anderson",
    "registrationNumber": "12000015",
    "universityEmail": "grace.anderson@university.edu",
    "personalEmail": "grace.anderson@gmail.com",
    "phone": "9876560738",
    "program": "MCA",
    "branch": "Electronics",
    "semester": "4",
    "cgpa": "9.0",
    "linkedin": "https://linkedin.com/in/graceanderson",
    "github": "https://github.com/graceanderson",
    "portfolio": "https://graceanderson.dev",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume15.pdf",
    "resumeFileId": "file_015",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.15",
    "communities": "IEEE",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 16
  },
  {
    "applicationId": "APP-016",
    "timestamp": "2026-08-25T11:19:09.964716Z",
    "status": "Pending",
    "fullName": "Bob Rodriguez",
    "registrationNumber": "12000016",
    "universityEmail": "bob.rodriguez@university.edu",
    "personalEmail": "bob.rodriguez@gmail.com",
    "phone": "9876527470",
    "program": "BBA",
    "branch": "Civil",
    "semester": "8",
    "cgpa": "8.0",
    "linkedin": "https://linkedin.com/in/bobrodriguez",
    "github": "https://github.com/bobrodriguez",
    "portfolio": "",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume16.pdf",
    "resumeFileId": "file_016",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.16",
    "communities": "ACM",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 17
  },
  {
    "applicationId": "APP-017",
    "timestamp": "2026-08-30T11:19:09.964720Z",
    "status": "Selected",
    "fullName": "Frank Taylor",
    "registrationNumber": "12000017",
    "universityEmail": "frank.taylor@university.edu",
    "personalEmail": "frank.taylor@gmail.com",
    "phone": "9876563915",
    "program": "BBA",
    "branch": "Civil",
    "semester": "4",
    "cgpa": "8.0",
    "linkedin": "https://linkedin.com/in/franktaylor",
    "github": "https://github.com/franktaylor",
    "portfolio": "https://franktaylor.dev",
    "preferredRole": "DevOps Engineer",
    "resumeUrl": "https://example.com/resume17.pdf",
    "resumeFileId": "file_017",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "2 years"
    },
    "ipAddress": "192.168.1.17",
    "communities": "GDSC",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 18
  },
  {
    "applicationId": "APP-018",
    "timestamp": "2026-08-23T11:19:09.964725Z",
    "status": "Rejected",
    "fullName": "Jack Davis",
    "registrationNumber": "12000018",
    "universityEmail": "jack.davis@university.edu",
    "personalEmail": "jack.davis@gmail.com",
    "phone": "9876599287",
    "program": "M.Tech",
    "branch": "Electronics",
    "semester": "8",
    "cgpa": "8.0",
    "linkedin": "https://linkedin.com/in/jackdavis",
    "github": "https://github.com/jackdavis",
    "portfolio": "",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume18.pdf",
    "resumeFileId": "file_018",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.18",
    "communities": "Open Source Society",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 19
  },
  {
    "applicationId": "APP-019",
    "timestamp": "2026-09-15T11:19:09.964730Z",
    "status": "Shortlisted",
    "fullName": "Leo Jackson",
    "registrationNumber": "12000019",
    "universityEmail": "leo.jackson@university.edu",
    "personalEmail": "leo.jackson@gmail.com",
    "phone": "9876562756",
    "program": "B.Tech",
    "branch": "Information Technology",
    "semester": "6",
    "cgpa": "7.2",
    "linkedin": "https://linkedin.com/in/leojackson",
    "github": "https://github.com/leojackson",
    "portfolio": "https://leojackson.dev",
    "preferredRole": "Cloud Architect",
    "resumeUrl": "https://example.com/resume19.pdf",
    "resumeFileId": "file_019",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "2 years"
    },
    "ipAddress": "192.168.1.19",
    "communities": "AWS Cloud Club",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 20
  },
  {
    "applicationId": "APP-020",
    "timestamp": "2026-08-28T11:19:09.964735Z",
    "status": "Interview Scheduled",
    "fullName": "John Johnson",
    "registrationNumber": "12000020",
    "universityEmail": "john.johnson@university.edu",
    "personalEmail": "john.johnson@gmail.com",
    "phone": "9876556089",
    "program": "MCA",
    "branch": "Information Technology",
    "semester": "8",
    "cgpa": "7.7",
    "linkedin": "https://linkedin.com/in/johnjohnson",
    "github": "https://github.com/johnjohnson",
    "portfolio": "https://johnjohnson.dev",
    "preferredRole": "UI/UX Designer",
    "resumeUrl": "https://example.com/resume20.pdf",
    "resumeFileId": "file_020",
    "roleAnswers": {
      "q1": "Experience varies",
      "q2": "4 years"
    },
    "ipAddress": "192.168.1.20",
    "communities": "ACM",
    "achievement": "Various achievements",
    "whyJoin": "To learn and grow.",
    "rowIndex": 21
  }
];

export async function getAllApplications(): Promise<Application[]> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 300));
  return MOCK_DATA;
}

export async function updateApplicationStatus(
  rowIndex: number,
  newStatus: string
): Promise<void> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 300));
  
  const index = MOCK_DATA.findIndex(a => a.rowIndex === rowIndex);
  if (index !== -1) {
    MOCK_DATA[index].status = newStatus as ApplicationStatus;
  } else {
    throw new Error('Application not found for row ' + rowIndex);
  }
}